version: "3.8"

services:
  rust-packet-analyser:
    build: rust-packet-analyser
    depends_on:
      - python-analyser-dashboard
    volumes:
      - ./pcap-files:/usr/src/app/data
    command: ["/usr/src/app/target/release/app"]
    networks:
      - app-network

  python-analyser-dashboard:
    build: python-analyser-dashboard
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
