[package]
name = "packet-analyser"
version = "0.1.0"
authors = ["Preetham Ananthkumar: preetham.mervin@gmail.com"]
edition = "2021"

[dependencies]
pnet = "0.30.0"
pcap = "0.10.0"

[[bin]]
name = "app"
path = "src/main.rs"

