[package]
name = "packet-analyser"
version = "0.1.0"
authors = ["iArcanic"]
edition = "2021"

[dependencies]
pnet = "0.30.0"
pcap = "0.10.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[[bin]]
name = "app"
path = "src/main.rs"
