[package]
name = "packet-analyser"
version = "0.1.0"
authors = ["Preetham Ananthkumar: preetham.mervin@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "app"
path = "src/main.rs"

